# Generated by Django 5.0.1 on 2024-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner-image')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment-image')),
            ],
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('count_apartment', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=3, verbose_name='Uyning balandligi')),
                ('parking', models.CharField(max_length=255)),
                ('repair', models.CharField(max_length=255)),
                ('class_housing', models.CharField(max_length=25)),
                ('balcony', models.BooleanField(default=False)),
                ('attenuation_system', models.CharField(max_length=255, verbose_name='Isitish tizimi')),
                ('territory', models.CharField(max_length=255, verbose_name='Hudud')),
                ('image', models.ManyToManyField(to='main.imageapartment')),
            ],
        ),
    ]
