# Generated by Django 5.0.1 on 2024-02-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bannerdiscount_contact_contactus_footer_goodrealtor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
