# Generated by Django 5.0.1 on 2024-02-16 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apartment_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='installments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.installments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='type_apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.typeapartment'),
            preserve_default=False,
        ),
    ]
