# Generated by Django 5.0.1 on 2024-02-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_apartment_installments_apartment_type_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.contactus'),
            preserve_default=False,
        ),
    ]
